name: fitmate
description: A Flutter health & fitness app with workouts, diet, mood tracking, and reminders.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_riverpod: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  flutter_local_notifications: ^16.1.0
  google_fonts: any
  intl: any
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
