// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk4fIywzSgR1ebsgvFCz5-AwF4eDPXXQM',
    appId: '1:520169008742:web:255630b7ad465d1ac3c7a7',
    messagingSenderId: '520169008742',
    projectId: 'fitmate-add',
    authDomain: 'fitmate-add.firebaseapp.com',
    storageBucket: 'fitmate-add.firebasestorage.app',
    measurementId: 'G-0MHVHKEEWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwwIzeKbLzTAJfy-O8ghxGwk6pVQwZFcQ',
    appId: '1:520169008742:android:490d4dbbd3bbf088c3c7a7',
    messagingSenderId: '520169008742',
    projectId: 'fitmate-add',
    storageBucket: 'fitmate-add.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9-1D1bW5fo2QV-HsiqHrHLq9kprQqlM',
    appId: '1:520169008742:ios:db89c53960ff1b15c3c7a7',
    messagingSenderId: '520169008742',
    projectId: 'fitmate-add',
    storageBucket: 'fitmate-add.firebasestorage.app',
    iosBundleId: 'com.example.fitmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9-1D1bW5fo2QV-HsiqHrHLq9kprQqlM',
    appId: '1:520169008742:ios:db89c53960ff1b15c3c7a7',
    messagingSenderId: '520169008742',
    projectId: 'fitmate-add',
    storageBucket: 'fitmate-add.firebasestorage.app',
    iosBundleId: 'com.example.fitmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk4fIywzSgR1ebsgvFCz5-AwF4eDPXXQM',
    appId: '1:520169008742:web:b58fdc9c9746774cc3c7a7',
    messagingSenderId: '520169008742',
    projectId: 'fitmate-add',
    authDomain: 'fitmate-add.firebaseapp.com',
    storageBucket: 'fitmate-add.firebasestorage.app',
    measurementId: 'G-ZJ7K26VJM7',
  );
}
